---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-llm-nebari-dev-v1alpha1-llmmodel
  failurePolicy: Fail
  name: vllmmodel-v1alpha1.kb.io
  rules:
  - apiGroups:
    - llm.nebari.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llmmodels
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-llm-nebari-dev-v1alpha1-passthroughmodel
  failurePolicy: Fail
  name: vpassthroughmodel-v1alpha1.kb.io
  rules:
  - apiGroups:
    - llm.nebari.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - passthroughmodels
  sideEffects: None
