{{- if .Values.keyManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebari-llm-serving.fullname" . }}-key-manager
  namespace: {{ include "nebari-llm-serving.operatorNamespace" . }}
  labels:
    {{- include "nebari-llm-serving.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "nebari-llm-serving.fullname" . }}-key-manager
{{- end }}
