{{- if .Values.keyManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nebari-llm-serving.fullname" . }}-key-manager
  namespace: {{ include "nebari-llm-serving.operatorNamespace" . }}
  labels:
    {{- include "nebari-llm-serving.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nebari-llm-serving.fullname" . }}-key-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "nebari-llm-serving.fullname" . }}-key-manager
    namespace: {{ include "nebari-llm-serving.operatorNamespace" . }}
{{- end }}
