apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nebari-llm-serving.fullname" . }}-operator
  namespace: {{ include "nebari-llm-serving.operatorNamespace" . }}
  labels:
    {{- include "nebari-llm-serving.labels" . | nindent 4 }}
